### ISSUE TITLE
Still can't use it 'cause i can't see it :)

### ISSUE THREAD

**Issue by roelvangils** [11ways/janeway#19]
This is how Janeway looks on my computer through my eyes:

![20220106_225854_iTerm2](https://user-images.githubusercontent.com/103744/148458295-327af3b8-f921-487e-89a5-e8e4c36e7dd9.png)

Could you maybe add different theme options or an option to not use colours?

**Comment by skerit** [comment]
This is because you reconfigured your terminal's `blue` color to look like white. (Which you did because you can't see blue text on a black background)

So first solution would be to choose a different replacement colour for blue.

But janeway already has a config file you can override. You can configure all the colours in there. Here's the default for the CLI:

![afbeelding](https://user-images.githubusercontent.com/755212/149315934-995929a5-24a6-4022-8f4f-ba5872b3c3fc.png)

The entire default config layout can be found in the README:

https://github.com/11ways/janeway#stored-configuration
